# Reference: https://github.com/ashishjoshi2605/ncsu-campus-jobs-review-system/blob/main/.github/workflows/pdoc.yml


name: documentation

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - run: pip install pdoc3
      - run: | 
            pdoc ./src/main.py -o ./docs
            pdoc ./src/num.py -o ./docs
            pdoc ./src/sym.py -o ./docs
            pdoc ./src/utils.py -o ./docs
            
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
